"use client";

import React, { useState } from 'react';
import { Typography, Button, Space, Row, Col, Card, Table, Tag, Divider } from 'antd';
import {
  RocketOutlined,
  ThunderboltOutlined,
  SyncOutlined,
  SafetyCertificateOutlined,
  GithubOutlined,
  LayoutOutlined,
} from '@ant-design/icons';
import { api } from "@/utils/api";
import { useStyles } from "./style";

export const dynamic = 'force-dynamic';

const { Title, Paragraph, Text } = Typography;

const Home = () => {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const { styles } = useStyles();

  const columns = [
    { title: "Date", dataIndex: "date", key: "date" },
    {
      title: "Temp (C)",
      dataIndex: "temperatureC",
      key: "temperatureC",
      render: (temp: number) => <Tag color={temp > 20 ? 'orange' : 'blue'}>{temp}°C</Tag>
    },
    { title: "Summary", dataIndex: "summary", key: "summary" },
  ];

  const getData = async () => {
    setLoading(true);
    try {
      const res = await api().getWeatherForecast();
      setData(res || []);
    } catch (error) {
      console.error("Failed to fetch data", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <section className={styles.hero}>
        <Title className={styles.heroTitle}>NextASP Boilerplate</Title>
        <Paragraph className={styles.heroSubtitle}>
          The ultimate full-stack starter kit combining the power of ASP.NET Core and the flexibility of Next.js.
          Type-safe, fast, and ready for production.
        </Paragraph>
        <Space size="middle">
          <Button type="primary" size="large" icon={<RocketOutlined />} ghost className={styles.heroCta} onClick={() => window.scrollTo({ top: 800, behavior: 'smooth' })}>
            Get Started
          </Button>
          <Button size="large" icon={<GithubOutlined />} href="https://github.com/lethabomaepa11/nextasp-boilerplate" target="_blank">
            View Source
          </Button>
        </Space>
      </section>

      <section className={styles.section}>
        <Title level={2} className={styles.sectionTitle}>Why NextASP?</Title>
        <Row gutter={[24, 24]}>
          <Col xs={24} md={8}>
            <Card className={styles.card}>
              <ThunderboltOutlined className={styles.icon} />
              <Title level={4}>Lightning Fast</Title>
              <Paragraph>
                Optimized with pnpm and Turborepo for instant starts and blazing fast builds.
              </Paragraph>
            </Card>
          </Col>
          <Col xs={24} md={8}>
            <Card className={styles.card}>
              <SafetyCertificateOutlined className={styles.icon} />
              <Title level={4}>End-to-End Type Safety</Title>
              <Paragraph>
                Orval reads your Swagger JSON and generates a fully typed TypeScript SDK directly from your C# controllers.
              </Paragraph>
            </Card>
          </Col>
          <Col xs={24} md={8}>
            <Card className={styles.card}>
              <LayoutOutlined className={styles.icon} />
              <Title level={4}>Modern UI Stack</Title>
              <Paragraph>
                Built with Ant Design and antd-style for a polished, responsive user experience out of the box.
              </Paragraph>
            </Card>
          </Col>
        </Row>
      </section>

      <section className={styles.usageSection}>
        <div className={styles.usageInner}>
          <Title level={2}>How to use it</Title>

          <Divider titlePlacement="left">1. Define your C# API</Divider>
          <Paragraph>
            Write your ASP.NET Core controllers as usual. Orval will pick up the Swagger docs automatically.
          </Paragraph>

          <Divider titlePlacement="left">2. Generate the SDK</Divider>
          <Paragraph>
            With your backend running, run Orval to generate typed functions for every endpoint:
          </Paragraph>
          <div className={styles.codeBlock}>
            pnpm sdk:generate
          </div>
          <Paragraph>
            <Text type="secondary">This reads your Swagger JSON at <Text code>http://localhost:5000/swagger/v1/swagger.json</Text> and produces a typed SDK.</Text>
          </Paragraph>
          <Paragraph>
            Orval generates an interface for each C# model and a typed function for each endpoint, all inside <Text code>packages/sdk/generated/index.ts</Text>:
          </Paragraph>
          <div className={styles.codeBlock}>
            <span className={styles.codeComment}>// Generated by orval — do not edit manually</span>
            <br />
            <span className={styles.codeKeyword}>export interface</span> <span className={styles.codeType}>WeatherForecast</span> {'{'}
            <br />
            &nbsp;&nbsp;date?: string;
            <br />
            &nbsp;&nbsp;temperatureC?: number;
            <br />
            &nbsp;&nbsp;readonly temperatureF?: number;
            <br />
            &nbsp;&nbsp;summary?: string | null;
            <br />
            {'}'}
            <br />
            <br />
            <span className={styles.codeKeyword}>export const</span> <span className={styles.codeFunc}>getBackend</span> = () =&gt; ({'{'}
            <br />
            &nbsp;&nbsp;<span className={styles.codeFunc}>getWeatherForecast</span>: () =&gt; {'{'}
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;<span className={styles.codeKeyword}>return</span> axiosInstance{'<'}<span className={styles.codeType}>WeatherForecast</span>[]{'>'}({'{'} url: <span className={styles.codeString}>"/WeatherForecast"</span>, method: <span className={styles.codeString}>"GET"</span> {'}'});
            <br />
            &nbsp;&nbsp;{'}'},
            <br />
            {'}'});
          </div>

          <Divider titlePlacement="left">3. Import and call in your frontend</Divider>
          <Paragraph>
            Import the generated client and call endpoints with full intellisense:
          </Paragraph>
          <div className={styles.codeBlock}>
            <span className={styles.codeKeyword}>import</span> {'{'} api {'}'} <span className={styles.codeKeyword}>from</span> <span className={styles.codeString}>"@/utils/api"</span>
            <br />
            <br />
            <span className={styles.codeComment}>// res is typed as WeatherForecast[]</span>
            <br />
            <span className={styles.codeKeyword}>const</span> res = <span className={styles.codeKeyword}>await</span> api().getWeatherForecast();
          </div>
        </div>
      </section>

      <section className={styles.section}>
        <Title level={2}>Live API Demo</Title>
        <Paragraph>
          Hit the button below to call the actual backend via the generated SDK.
        </Paragraph>

        <div className={styles.demoSection}>
          <Space direction="vertical" className={styles.fullWidth} size="large">
            <Button
              type="primary"
              icon={<SyncOutlined spin={loading} />}
              onClick={getData}
              loading={loading}
              className={styles.fetchBtn}
            >
              Fetch Weather Forecast
            </Button>

            <Table
              dataSource={data}
              columns={columns}
              rowKey="date"
              scroll={{ x: true }}
              pagination={false}
              bordered
            />
          </Space>
        </div>
      </section>

      <footer className={styles.footer}>
        NextASP Boilerplate ©{new Date().getFullYear()} Created with ❤️
      </footer>
    </div>
  );
};

export default Home;
